/** Extension / filename → highlighter language id (Shiki ids, which lowlight/highlight.js share for these). */

const BY_EXT: Record<string, string> = {
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  jsx: "jsx",
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "tsx",
  json: "json",
  jsonc: "json",
  json5: "json",
  md: "markdown",
  markdown: "markdown",
  mdx: "mdx",
  html: "html",
  htm: "html",
  vue: "vue",
  svelte: "svelte",
  astro: "astro",
  css: "css",
  scss: "scss",
  sass: "sass",
  less: "less",
  py: "python",
  pyi: "python",
  rb: "ruby",
  gemspec: "ruby",
  go: "go",
  rs: "rust",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  scala: "scala",
  groovy: "groovy",
  gradle: "groovy",
  swift: "swift",
  m: "objective-c",
  mm: "objective-cpp",
  c: "c",
  h: "c",
  cc: "cpp",
  cpp: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  hh: "cpp",
  hxx: "cpp",
  cs: "csharp",
  fs: "fsharp",
  php: "php",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  fish: "fish",
  ps1: "powershell",
  psm1: "powershell",
  bat: "bat",
  cmd: "bat",
  yaml: "yaml",
  yml: "yaml",
  toml: "toml",
  ini: "ini",
  cfg: "ini",
  conf: "ini",
  env: "ini",
  properties: "properties",
  xml: "xml",
  xsl: "xml",
  xsd: "xml",
  plist: "xml",
  svg: "xml",
  csproj: "xml",
  sql: "sql",
  graphql: "graphql",
  gql: "graphql",
  proto: "protobuf",
  lua: "lua",
  dart: "dart",
  r: "r",
  pl: "perl",
  pm: "perl",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  hs: "haskell",
  clj: "clojure",
  cljs: "clojure",
  cljc: "clojure",
  elm: "elm",
  ml: "ocaml",
  mli: "ocaml",
  jl: "julia",
  tf: "hcl",
  hcl: "hcl",
  nix: "nix",
  zig: "zig",
  sol: "solidity",
  tex: "latex",
  vim: "viml",
  diff: "diff",
  patch: "diff",
  cmake: "cmake",
  dockerfile: "dockerfile",
  makefile: "makefile",
  mk: "makefile",
  txt: "text",
  log: "text",
  lock: "text",
  csv: "csv",
  wgsl: "wgsl",
  glsl: "glsl",
  prisma: "prisma",
};

const BY_NAME: Record<string, string> = {
  dockerfile: "dockerfile",
  containerfile: "dockerfile",
  makefile: "makefile",
  gnumakefile: "makefile",
  "cmakelists.txt": "cmake",
  gemfile: "ruby",
  rakefile: "ruby",
  podfile: "ruby",
  brewfile: "ruby",
  vagrantfile: "ruby",
  ".gitignore": "text",
  ".gitattributes": "text",
  ".gitmodules": "ini",
  ".editorconfig": "ini",
  ".npmrc": "ini",
  ".bashrc": "bash",
  ".zshrc": "bash",
  ".bash_profile": "bash",
  ".babelrc": "json",
  ".eslintrc": "json",
  ".prettierrc": "json",
  "package.json": "json",
};

export function languageFor(path: string): string {
  const base = path.slice(path.lastIndexOf("/") + 1).toLowerCase();
  const byName = BY_NAME[base];
  if (byName) return byName;
  const dot = base.lastIndexOf(".");
  if (dot === -1) return "text";
  return BY_EXT[base.slice(dot + 1)] ?? "text";
}
